name: todolist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5
  hive: ^1.4.1+1
  path_provider: ^1.6.7
  flutter_svg: ^0.17.4
  pedantic: ^1.8.0+1
  flutter_neumorphic: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/